import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { getString } from './argv.js';

/** A minimal GitHub PR comment poster. */
export class GitHubCommenter {
  private readonly token: string;
  private readonly apiBase: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: { token?: string; apiBase?: string; fetchImpl?: typeof fetch } = {}) {
    this.token = options.token ?? '';
    this.apiBase = options.apiBase ?? 'https://api.github.com';
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  async postComment(options: {
    owner: string;
    repo: string;
    prNumber: number;
    body: string;
  }): Promise<{ id: number; url: string }> {
    const url = `${this.apiBase}/repos/${options.owner}/${options.repo}/issues/${options.prNumber}/comments`;
    const res = await this.fetchImpl(url, {
      method: 'POST',
      headers: {
        accept: 'application/vnd.github+json',
        authorization: `Bearer ${this.token}`,
        'content-type': 'application/json',
        'x-github-api-version': '2022-11-28',
        'user-agent': 'crucible-cli',
      },
      body: JSON.stringify({ body: options.body }),
    });
    if (!res.ok) {
      throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
    }
    const data = (await res.json()) as { id: number; html_url: string };
    return { id: data.id, url: data.html_url };
  }
}

/** Format a markdown summary suitable for posting on a PR. */
export function formatPRComment(
  findings: Array<{
    severity: string;
    title: string;
    message: string;
    file?: string;
    line?: number;
  }>,
  consensus: number,
): string {
  const counts = findings.reduce<Record<string, number>>((acc, f) => {
    acc[f.severity] = (acc[f.severity] ?? 0) + 1;
    return acc;
  }, {});
  const summary = Object.entries(counts)
    .map(([k, n]) => `\`${k}\`: ${n}`)
    .join(' · ');
  const lines: string[] = [];
  lines.push('## :fire: Crucible review');
  lines.push('');
  lines.push(`- **Score:** ${consensus.toFixed(2)}`);
  lines.push(`- **Findings:** ${findings.length}`);
  if (summary) lines.push(`- **Breakdown:** ${summary}`);
  lines.push('');
  if (findings.length === 0) {
    lines.push('_No findings._');
  } else {
    for (const f of findings.slice(0, 20)) {
      const loc = f.file ? `\`${f.file}${f.line ? `:${f.line}` : ''}\` · ` : '';
      lines.push(`- **${f.severity.toUpperCase()}** ${loc}${f.title}`);
      if (f.message) {
        const msg = f.message.length > 200 ? `${f.message.slice(0, 197)}...` : f.message;
        lines.push(`  > ${msg}`);
      }
    }
    if (findings.length > 20) {
      lines.push(`\n_...and ${findings.length - 20} more._`);
    }
  }
  lines.push('');
  lines.push('<sub>Generated by [Crucible](https://github.com/10xdev4u-alt/crucible)</sub>');
  return lines.join('\n');
}

export function cmdPost(
  _positionals: string[],
  flags: Record<string, string | boolean | string[]>,
): Promise<number> {
  const token = process.env.GITHUB_TOKEN ?? getString(flags, 'token');
  const summaryPath = getString(flags, 'input', './crucible-summary.md');
  if (!token) {
    console.error('GITHUB_TOKEN env var or --token required');
    return Promise.resolve(1);
  }
  if (!existsSync(summaryPath)) {
    console.error(`Summary file not found: ${summaryPath}`);
    return Promise.resolve(1);
  }
  const body = readFileSync(summaryPath, 'utf8');
  const owner = getString(flags, 'owner', process.env.GITHUB_REPOSITORY?.split('/')[0] ?? '');
  const repo = getString(flags, 'repo', process.env.GITHUB_REPOSITORY?.split('/')[1] ?? '');
  const pr = Number.parseInt(getString(flags, 'pr', process.env.PR_NUMBER ?? ''), 10);
  if (!owner || !repo || !Number.isFinite(pr)) {
    console.error('--owner, --repo, and --pr (or GITHUB_REPOSITORY + PR_NUMBER) required');
    return Promise.resolve(1);
  }
  return new GitHubCommenter({ token })
    .postComment({ owner, repo, prNumber: pr, body })
    .then((r) => {
      console.log(`Posted comment: ${r.url}`);
      const out = getString(flags, 'output');
      if (out) writeFileSync(resolve(process.cwd(), out), JSON.stringify(r, null, 2), 'utf8');
      return 0;
    })
    .catch((err: unknown) => {
      console.error('Failed to post comment:', err);
      return 1;
    });
}
